server:
  port: 3808
  error:
    whitelabel:
      enabled: false

#spring:
#  data:
#    #___MONGODB___
#    mongodb:
#      host: 192.168.0.140
#      port: 27017
#      database: cvikl
#      repositories:
#        enabled: true